#!/usr/bin/env python
import sys
import argparse
import yaml
import netgen
import voluptuous

def main():
    outplugins = {
        'text': netgen.output.Text,
        'bind': netgen.output.Bind,
    }
    ap = argparse.ArgumentParser(description='generate')
    ap.add_argument('--zone', metavar='ZONE', type=str, required=True)
    ap.add_argument('--config', metavar='config.yaml',
                    type=str, default='config.yaml')
    ap.add_argument('--output', metavar='|'.join(outplugins.keys()),
                    type=str, choices=outplugins.keys(), default='text')
    args = ap.parse_args()

    with open(args.config) as config_fd:
        config = yaml.load(config_fd)
        schema = voluptuous.Schema({
            str: {
                'type': str,
                'network': voluptuous.Match('^[0-9.]+/[0-9]{1,2}$')
            }
        })
        schema(config)
        if args.zone not in config:
            sys.exit('zone "{}" does not exists'.format(args.zone))
        zone = config[args.zone]
        topology = netgen.Topology(zone['type'], args.zone, zone['network'])
        netgen.NetworkGenerator(topology).output(outplugins[args.output])

if __name__ == '__main__':
    main()
